services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/db
      - MINIO_URL=minio:9000
      - MINIO_EXTERNAL_HOST=localhost:9000
    env_file:
      - .env

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: docker.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: secure_password123
    command: server /data
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data: